// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace gambit
{
    namespace Gambit
    {
        namespace PVector
        {
            [StructLayout(LayoutKind.Sequential, Size = 56)]
            public unsafe partial struct __Internal
            {
                internal __IntPtr vfptr_Array;
                internal int mindex;
                internal int maxdex;
                internal __IntPtr data;
                internal __IntPtr svptr;
                internal global::gambit.Gambit.Array.__Internal svlen;
            }
        }

        public unsafe partial class PVector<T> : global::gambit.Gambit.Vector<T>, IDisposable
        {
            internal static new PVector<T> __CreateInstance(__IntPtr native, bool skipVTables = false)
            {
                if (native == __IntPtr.Zero)
                    return null;
                return new PVector<T>(native.ToPointer(), skipVTables);
            }

            internal static new PVector<T> __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
            {
                if (native == __IntPtr.Zero)
                    return null;
                if (__TryGetNativeToManagedMapping(native, out var managed))
                    return (PVector<T>)managed;
                var result = __CreateInstance(native, skipVTables);
                if (saveInstance)
                    __RecordNativeToManagedMapping(native, result);
                return result;
            }

            internal static PVector<T> __CreateInstance(global::gambit.Gambit.PVector.__Internal native, bool skipVTables = false)
            {
                return new PVector<T>(native, skipVTables);
            }

            private static void* __CopyValue(global::gambit.Gambit.PVector.__Internal native)
            {
                var ret = Marshal.AllocHGlobal(sizeof(global::gambit.Gambit.PVector.__Internal));
                *(global::gambit.Gambit.PVector.__Internal*) ret = native;
                return ret.ToPointer();
            }

            private PVector(global::gambit.Gambit.PVector.__Internal native, bool skipVTables = false)
                : this(__CopyValue(native), skipVTables)
            {
                __ownsNativeInstance = true;
                __RecordNativeToManagedMapping(__Instance, this);
            }

            protected PVector(void* native, bool skipVTables = false)
                : base((void*) native)
            {
            }

            public PVector()
                : this((void*) null)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method PVector_T_ ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public PVector(global::gambit.Gambit.Array<int> sig)
                : this((void*) null)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method PVector_T_ ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public PVector(global::gambit.Gambit.Vector<T> val, global::gambit.Gambit.Array<int> sig)
                : this((void*) null)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method PVector_T_ ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public PVector(global::gambit.Gambit.PVector<T> v)
                : this((void*) null)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method PVector_T_ ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            partial void DisposePartial(bool disposing);

            internal protected override void Dispose(bool disposing, bool callNativeDtor )
            {
                if (__Instance == IntPtr.Zero)
                    return;
                NativeToManagedMap.TryRemove(__Instance, out _);
                DisposePartial(disposing);
                if (__ownsNativeInstance)
                    Marshal.FreeHGlobal(__Instance);
                __Instance = IntPtr.Zero;
            }

            protected int Check(global::gambit.Gambit.PVector<T> v)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method Check ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public global::gambit.Gambit.Vector<T> GetRow(int row)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method GetRow ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public void GetRow(int row, global::gambit.Gambit.Vector<T> v)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method GetRow ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public void SetRow(int row, global::gambit.Gambit.Vector<T> v)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method SetRow ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public void CopyRow(int row, global::gambit.Gambit.PVector<T> v)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method CopyRow ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public static global::gambit.Gambit.PVector<T> operator +(global::gambit.Gambit.PVector<T> __op, global::gambit.Gambit.PVector<T> v)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method operator_ ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public static global::gambit.Gambit.PVector<T> operator -(global::gambit.Gambit.PVector<T> __op, global::gambit.Gambit.PVector<T> v)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method operator_ ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public static T operator *(global::gambit.Gambit.PVector<T> __op, global::gambit.Gambit.PVector<T> v)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method operator_ ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public static global::gambit.Gambit.PVector<T> operator /(global::gambit.Gambit.PVector<T> __op, T c)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method operator_ ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public static bool operator ==(global::gambit.Gambit.PVector<T> __op, global::gambit.Gambit.PVector<T> v)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method operator__ ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public override bool Equals(object obj)
            {
                return this == obj as global::gambit.Gambit.PVector<T>;
            }

            public override int GetHashCode()
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    if (__Instance == __IntPtr.Zero)
                        return __IntPtr.Zero.GetHashCode();
                    return (*(global::gambit.Gambit.PVector.__Internal*) __Instance).GetHashCode();
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public static bool operator !=(global::gambit.Gambit.PVector<T> __op, global::gambit.Gambit.PVector<T> v)
            {
                var __T = typeof(T);
                if (__T.IsAssignableFrom(typeof(int)))
                {
                    throw new MissingMethodException("Method operator__ ignored in specialization global::gambit.Gambit.PVector<int>.");
                }
                throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
            }

            public static explicit operator global::gambit.Gambit.PVector<T>(global::gambit.Gambit.Array<int> sig)
            {
                return new global::gambit.Gambit.PVector<T>(sig);
            }

            protected T Svptr
            {
                get
                {
                    var __T = typeof(T);
                    if (__T.IsAssignableFrom(typeof(int)))
                    {
                        return (T) (object) ((global::gambit.Gambit.PVector.__Internal*)__Instance)->svptr;
                    }
                    throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
                }

                set
                {
                    var __T = typeof(T);
                    if (__T.IsAssignableFrom(typeof(int)))
                    {
                        var __value0 = (int) (object) value;
                        ((global::gambit.Gambit.PVector.__Internal*)__Instance)->svptr = (__IntPtr) (object) __value0;
                        return;
                    }
                    throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
                }
            }

            protected global::gambit.Gambit.Array<int> Svlen
            {
                get
                {
                    var __T = typeof(T);
                    if (__T.IsAssignableFrom(typeof(int)))
                    {
                        return global::gambit.Gambit.Array<int>.__CreateInstance(new __IntPtr(&((global::gambit.Gambit.PVector.__Internal*)__Instance)->svlen));
                    }
                    throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
                }

                set
                {
                    var __T = typeof(T);
                    if (__T.IsAssignableFrom(typeof(int)))
                    {
                        if (ReferenceEquals(value, null))
                            throw new global::System.ArgumentNullException("value", "Cannot be null because it is passed by value.");
                        ((global::gambit.Gambit.PVector.__Internal*)__Instance)->svlen = *(global::gambit.Gambit.Array.__Internal*) value.__Instance;
                        return;
                    }
                    throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
                }
            }

            public global::gambit.Gambit.Array<int> Lengths
            {
                get
                {
                    var __T = typeof(T);
                    if (__T.IsAssignableFrom(typeof(int)))
                    {
                        throw new MissingMethodException("Method Lengths missing from explicit specialization global::gambit.Gambit.PVector<int>.");
                    }
                    throw new ArgumentOutOfRangeException("T", string.Join(", ", new[] { typeof(T).FullName }), "global::gambit.Gambit.PVector<T> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <int>.");
                }
            }
        }

        public unsafe static partial class PVectorExtensions
        {
            public partial struct __Internal
            {
            }
        }
    }
}
