// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace gambit
{
    public unsafe partial class sharpgambit
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity, DllImport("sharpgambit", EntryPoint = "NewEmptyGame", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr NewEmptyGame();

            [SuppressUnmanagedCodeSecurity, DllImport("sharpgambit", EntryPoint = "NewGame", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr NewGame([MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(CppSharp.Runtime.UTF8Marshaller))] string title, int pc, [MarshalAs(UnmanagedType.LPArray)] string[] players);

            [SuppressUnmanagedCodeSecurity, DllImport("sharpgambit", EntryPoint = "AddPlayerToGame", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr AddPlayerToGame(__IntPtr game);

            [SuppressUnmanagedCodeSecurity, DllImport("sharpgambit", EntryPoint = "GetPlayer", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr GetPlayer(__IntPtr game, int pi);

            [SuppressUnmanagedCodeSecurity, DllImport("sharpgambit", EntryPoint = "GetPlayerTitle", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr GetPlayerTitle(__IntPtr player);

            [SuppressUnmanagedCodeSecurity, DllImport("sharpgambit", EntryPoint = "SetPlayerTitle", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr SetPlayerTitle(__IntPtr player, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(CppSharp.Runtime.UTF8Marshaller))] string label);
        }

        public static __IntPtr NewEmptyGame()
        {
            var ___ret = __Internal.NewEmptyGame();
            return ___ret;
        }

        public static __IntPtr NewGame(string title, int pc, string[] players)
        {
            var ___ret = __Internal.NewGame(title, pc, players);
            return ___ret;
        }

        public static __IntPtr AddPlayerToGame(__IntPtr game)
        {
            var ___ret = __Internal.AddPlayerToGame(game);
            return ___ret;
        }

        public static __IntPtr GetPlayer(__IntPtr game, int pi)
        {
            var ___ret = __Internal.GetPlayer(game, pi);
            return ___ret;
        }

        public static string GetPlayerTitle(__IntPtr player)
        {
            var ___ret = __Internal.GetPlayerTitle(player);
            return CppSharp.Runtime.MarshalUtil.GetString(global::System.Text.Encoding.UTF8, ___ret);
        }

        public static __IntPtr SetPlayerTitle(__IntPtr player, string label)
        {
            var ___ret = __Internal.SetPlayerTitle(player, label);
            return ___ret;
        }
    }
}
